import { AntDesign } from '@expo/vector-icons';
import { Entypo } from '@expo/vector-icons';
import { EvilIcons } from '@expo/vector-icons';
import { Feather } from '@expo/vector-icons';
import { FontAwesome } from '@expo/vector-icons';
import { FontAwesome5 } from '@expo/vector-icons';
import { Fontisto } from '@expo/vector-icons';
import { Foundation } from '@expo/vector-icons';
import { Ionicons } from '@expo/vector-icons';
import { MaterialCommunityIcons } from '@expo/vector-icons';
import { MaterialIcons } from '@expo/vector-icons';
import { Octicons } from '@expo/vector-icons';
import { SimpleLineIcons } from '@expo/vector-icons';
import { Zocial } from '@expo/vector-icons';

export const AD = AntDesign;
export const ETP = Entypo;
export const EI = EvilIcons;
export const FT = Feather;
export const FA = FontAwesome;
export const FA5 = FontAwesome5;
export const FI = Fontisto;
export const FD = Foundation;
export const II = Ionicons;
export const MCI = MaterialCommunityIcons;
export const MI = MaterialIcons;
export const OI = Octicons;
export const SLI = SimpleLineIcons;
export const ZC = Zocial;
