export const queryKeys = {
  loadMe: 'loadMe',
  mySpaces: 'mySpaces',
  logs: 'logs',
  createPost: 'createPost',
  updateSpaceCheckedInDate: 'updateSpaceCheckedInDate',
  members: 'members',
  postsByTagId: 'postsByTagId',
  momentsBySpaceId: 'momentsBySpaceId',
  spaceBySecretKey: 'spaceBySecretKey',
  stickers: 'stickers',
  postsByUserId: 'postsByUserId',
  userById: 'userById',
  postsByUserIdAndRegion: 'postsByUserIdAndRegion',
  commentsByPostId: 'commentsByPostId',
  reactionsByPostId: 'reactionsByPostId',
  postsByTagIdAndRegion: 'postsByTagIdAndRegion',
  spaceById: 'spaceById',
  // ここら辺のkey名、apiのエンドポイントに則った方がいいよね多分。
};
