export const atomKeys = {
  auth: 'auth',
  appState: 'appState',
  isPushNotificationEnabled: 'isPushNotificationEnabled',
  viewPostsType: 'viewPostsType',
  currentPost: 'currentPost',
  currentMapPost: 'currentMapPost',
  screenLoaded: 'screenLoaded',
  postsByTagIdAndRegion: 'postsByTagIdAndRegion',
  currentRegion: 'currentRegion',
  currentPostIndex: 'currentPostIndex',
  currentRegionPostIndex: 'currentRegionPostIndex',
  createPost: 'createPost',
  tagScreenOpened: 'tagScreenOpened',
  getMoments: 'getMoments',
  createMoment: 'createMoment',
  getReactionsByPostId: 'getReactionsByPostId',
  momentLogs: 'momentLogs',
  mySpaces: 'mySpaces',
  currentSpace: 'currentSpace',
  logsTable: 'logsTable',
  currentTag: 'currentTag',
  currentPostsPageByTagId: 'currentPostsPageByTagId',
};
