export const atomKeys = {
  viewPostsType: 'viewPostsType',
  currentPost: 'currentPost',
  currentMapPost: 'currentMapPost',
  screenLoaded: 'screenLoaded',
  postsByTagIdAndRegion: 'postsByTagIdAndRegion',
  currentRegion: 'currentRegion',
  currentPostIndex: 'currentPostIndex',
  currentRegionPostIndex: 'currentRegionPostIndex',
  createPost: 'createPost',
  tagScreenOpened: 'tagScreenOpened',
  getMoments: 'getMoments',
  createMoment: 'createMoment',
  getReactionsByPostId: 'getReactionsByPostId',
  momentLogs: 'momentLogs',
  mySpaces: 'mySpaces',
};
